services:
  arrows:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: "production"
        BUNDLE_WITHOUT: "development test"
    container_name: arrows_production
    ports:
      - "3001:3000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      # --- LÍNEAS DE FUERZA BRUTA (Mantenlas) ---
      - BUNDLE_PATH=/gems 
      - GEM_HOME=/gems
      # --- LA LÍNEA FINAL QUE FALTA ---
      - BUNDLE_WITHOUT=development:test
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    command: >
      sh -c "
      bundle exec rails db:migrate &&
      bundle exec rails s -b 0.0.0.0 -p 3000
      "
    restart: always

  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: "production"
        BUNDLE_WITHOUT: "development test"
    container_name: sidekiq_production
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      # --- LÍNEAS DE FUERZA BRUTA (Mantenlas) ---
      - BUNDLE_PATH=/gems
      - GEM_HOME=/gems
      # --- LA LÍNEA FINAL QUE FALTA ---
      - BUNDLE_WITHOUT=development:test
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    command: >
      sh -c "
      bundle exec sidekiq -C config/sidekiq.yml
      "
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_production
    env_file:
      - .env
    command: >
      sh -c "
      redis-server --requirepass \"$REDIS_PASSWORD\"
      "
    restart: unless-stopped