version: '3.7'

services:
  solace:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: "production"
        BUNDLE_WITHOUT: "development test"
    container_name: solace_production

    ports:
      - "3001:3000"

    depends_on:
      - redis
    env_file:
      - .env.production
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

    command: >
      sh -c "
      bundle exec rails db:migrate &&
      bundle exec rails s -b 0.0.0.0 -p 3000
      "

  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RAILS_ENV: "production"
        BUNDLE_WITHOUT: "development test"
    container_name: sidekiq_production

    depends_on:
      - redis
    env_file:
      - .env.production
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0

    command: >
      sh -c "
      bundle exec sidekiq -C config/sidekiq.yml
      "

  redis:
    image: redis:7-alpine
    container_name: redis_production
    env_file:
      - .env.production
    command: sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    restart: unless-stopped
