name: Deploy to Staging

on:
  push:
    branches:
      - stg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.STG_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.STG_USER }}@${{ secrets.STG_HOST }} "echo 'Conexión SSH exitosa'"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.STG_HOST }}
          username: solace
          key: ${{ secrets.STG_SSH_KEY }}
          script: |
            # Navegar a la carpeta donde está el proyecto
            cd /home/solace/solace

            # Si el repositorio no está clonado, clonarlo; de lo contrario, actualizarlo
            if [ ! -d ".git" ]; then
              git clone git@github.com:nuuxia/solace.git .
            else
              git fetch origin stg
              git reset --hard origin/stg
            fi

            export REDIS_PASSWORD=${{ secrets.STG_REDIS_PASSWORD }}

            # Levantar los contenedores utilizando docker-compose.yaml y el archivo .env
            docker compose up -d --build
