name: Deploy to Production

on:
  push:
    branches:
      - production  # Se ejecuta cada vez que se sube código a production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/nuuxia/nuuxia-chat  # Ajusta la ruta si es diferente en tu server
            git pull origin production
            docker-compose -f docker-compose.production.yaml up -d --build
